# Generated by Django 4.0.5 on 2022-06-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры и режиссеры', 'verbose_name_plural': 'Актеры и режиссеры'},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='start',
            new_name='star',
        ),
    ]
