# Generated by Django 4.0.5 on 2022-07-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_options_rename_start_rating_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='bros',
            field=models.ManyToManyField(blank=True, to='movies.actor'),
        ),
    ]
