# Generated by Django 4.0.5 on 2022-07-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_actor_bros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезд рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
